# -*- coding: utf-8 -*-
"""Ejer4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gn0NQRY-u7hhfe5YKcR50ry5kyHWk5zH
"""

import numpy as np
from scipy.sparse import csr_matrix
rows, cols = 1000, 1000
density = 0.01
matriz1_data = np.random.binomial(1, density, size=(rows, cols))
matriz2_data = np.random.binomial(1, density, size=(rows, cols))
matrizsparce1 = csr_matrix(matriz1_data)
matrizsparce2 = csr_matrix(matriz2_data)

# Multiplicación de matrices dispersas por filas
res = csr_matrix((rows, cols))
for i in range(rows):
    row_vector =matrizsparce1.getrow(i)
    result_row = row_vector.dot(matrizsparce2)
    res[i] = result_row

print(res)